ebean:
  test:
    platform: mysql #, h2, postgres, mysql, oracle, sqlserver, hana, clickhouse, sqlite
    ddlMode: none # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: test